from enum import Enum
from pydantic import BaseModel, Field, model_validator


class OcrConfidence(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class OcrResult(BaseModel):
    extracted_text: str = Field(description="The transcribed text of the handwritten answer")
    confidence: OcrConfidence
    is_illegible: bool = Field(
        description="True if part or all of the answer could not be confidently transcribed"
    )
    notes: str | None = Field(
        default=None,
        description="Explanation of what's illegible or uncertain; required if is_illegible is True",
    )

    @model_validator(mode="after")
    def _illegible_requires_notes(self) -> "OcrResult":
        if self.is_illegible and not self.notes:
            raise ValueError("notes is required when is_illegible is True")
        return self


class RubricItemStatus(str, Enum):
    MET = "met"
    PARTIALLY_MET = "partially_met"
    MISSED = "missed"
    NOT_APPLICABLE = "not_applicable"


class RubricItemResult(BaseModel):
    criterion: str = Field(description="The rubric criterion being judged, verbatim from the rubric")
    status: RubricItemStatus
    points_awarded: float = Field(ge=0)
    points_possible: float = Field(gt=0)
    evidence: str = Field(description="Quote or paraphrase from the student answer supporting this judgment")
    box_2d: list[int] | None = Field(
        default=None,
        description="[ymin, xmin, ymax, xmax] normalized 0-1000, locating the exact text on the "
        "source image this judgment's evidence refers to. Only set when grading from an image; "
        "None for text-only grading.",
    )


class GradingResult(BaseModel):
    total_score: float = Field(ge=0)
    total_possible: float = Field(gt=0)
    rubric_results: list[RubricItemResult]
    overall_rationale: str = Field(description="Short summary of why this score was given")
    is_ambiguous: bool = Field(
        description="True if the answer is genuinely unclear/contradictory and a human should review it"
    )
    ambiguity_reason: str | None = Field(
        default=None, description="Required if is_ambiguous is True; explains what's unclear"
    )
    corrected_answer: str | None = Field(
        default=None,
        description="If the student's answer had a fixable error, a corrected version of the key parts; "
        "otherwise None",
    )

    @model_validator(mode="after")
    def _ambiguity_requires_reason(self) -> "GradingResult":
        if self.is_ambiguous and not self.ambiguity_reason:
            raise ValueError("ambiguity_reason is required when is_ambiguous is True")
        return self

    @model_validator(mode="after")
    def _points_within_bounds(self) -> "GradingResult":
        for item in self.rubric_results:
            if item.points_awarded > item.points_possible:
                raise ValueError(
                    f"points_awarded ({item.points_awarded}) exceeds points_possible "
                    f"({item.points_possible}) for criterion {item.criterion!r}"
                )
        return self


class RubricItem(BaseModel):
    criterion: str
    points: float = Field(gt=0)


class SubjectPreset(BaseModel):
    subject: str
    grading_instructions: str = Field(
        description="Subject-specific grading guidance appended to the engine's system prompt"
    )


class GradingRequest(BaseModel):
    question: str
    reference_answer: str
    rubric: list[RubricItem]
    student_answer: str = ""
    student_answer_image_path: str | None = Field(
        default=None,
        description="Path to a handwritten answer image; if set and student_answer is empty, "
        "grade_file.py OCRs this image first to fill student_answer",
    )
    subject: str = "general"

    @model_validator(mode="after")
    def _answer_or_image_required(self) -> "GradingRequest":
        if not self.student_answer and not self.student_answer_image_path:
            raise ValueError("either student_answer or student_answer_image_path is required")
        return self


class GradeConfidence(str, Enum):
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class ScriptQuestionResult(BaseModel):
    question_text: str = Field(description="The question as found in the script, verbatim or paraphrased")
    student_answer_as_written: str = Field(description="The student's answer to this question, transcribed")
    criteria: list[RubricItemResult] = Field(
        description="2-4 specific criteria this question is graded against, generated by the grader "
        "itself (no teacher-supplied rubric for this flow) — e.g. 'correct formula used', 'correct "
        "final answer', 'units included'. Every point awarded or lost must cite one of these, not a "
        "free-floating judgment call."
    )
    explanation: str = Field(description="Why the answer is correct or incorrect, referencing the criteria")
    correction: str | None = Field(
        default=None, description="The correct answer/fix, if any criteria were missed; otherwise None"
    )
    concept: str = Field(
        description="Short tag (2-5 words) for the underlying concept this question tests, e.g. "
        "'quadratic factoring' or 'thread synchronization' — used to track recurring weak areas"
    )
    confidence: GradeConfidence = Field(
        description="How confident the grader is in this specific judgment. LOW/MEDIUM should be "
        "honest, not rare — use them whenever handwriting is unclear, the method is unusual but "
        "possibly valid, or the correctness call is a genuine judgment rather than a clear fact."
    )
    needs_human_review: bool = Field(
        description="True if a human should check this one before the grade is trusted — typically "
        "whenever confidence is not HIGH"
    )
    review_reason: str | None = Field(
        default=None,
        description="Required if needs_human_review is True; explains specifically what's uncertain "
        "(e.g. 'last two lines illegible', 'method is nonstandard, may still be valid')",
    )

    @model_validator(mode="after")
    def _review_requires_reason(self) -> "ScriptQuestionResult":
        if self.needs_human_review and not self.review_reason:
            raise ValueError("review_reason is required when needs_human_review is True")
        return self

    @property
    def points_awarded(self) -> float:
        return sum(c.points_awarded for c in self.criteria)

    @property
    def points_possible(self) -> float:
        return sum(c.points_possible for c in self.criteria)

    @property
    def is_correct(self) -> bool:
        return self.points_possible > 0 and self.points_awarded >= self.points_possible

    def to_dict(self) -> dict:
        """model_dump() plus the computed points/correctness — for API responses and any other
        consumer that needs the derived totals alongside the raw criteria."""
        return {
            **self.model_dump(),
            "is_correct": self.is_correct,
            "points_awarded": self.points_awarded,
            "points_possible": self.points_possible,
        }


class ScriptGradingResult(BaseModel):
    questions: list[ScriptQuestionResult]
    overall_summary: str = Field(description="Short summary of overall performance across the script")
    score_estimate: str = Field(description="e.g. '7/10 questions correct' — a rough tally, not a rubric score")

    @property
    def flagged_count(self) -> int:
        return sum(1 for q in self.questions if q.needs_human_review)

    @property
    def total_points_awarded(self) -> float:
        return sum(q.points_awarded for q in self.questions)

    @property
    def total_points_possible(self) -> float:
        return sum(q.points_possible for q in self.questions)

    def to_dict(self) -> dict:
        return {
            "questions": [q.to_dict() for q in self.questions],
            "overall_summary": self.overall_summary,
            "score_estimate": self.score_estimate,
            "flagged_count": self.flagged_count,
            "total_points_awarded": self.total_points_awarded,
            "total_points_possible": self.total_points_possible,
        }


class HumanRubricJudgment(BaseModel):
    criterion: str = Field(description="The rubric criterion being judged, verbatim from the rubric")
    status: RubricItemStatus
    points_awarded: float = Field(ge=0)
    points_possible: float = Field(gt=0)

    @model_validator(mode="after")
    def _points_within_bounds(self) -> "HumanRubricJudgment":
        if self.points_awarded > self.points_possible:
            raise ValueError(
                f"points_awarded ({self.points_awarded}) exceeds points_possible "
                f"({self.points_possible}) for criterion {self.criterion!r}"
            )
        return self


class EvalCase(BaseModel):
    case_id: str
    request: GradingRequest
    human_judgments: list[HumanRubricJudgment]

    @property
    def human_total_score(self) -> float:
        return sum(j.points_awarded for j in self.human_judgments)


class AdversarialTrap(str, Enum):
    """The category of trick an adversarial test case is probing for."""

    RIGHT_ANSWER_WRONG_REASONING = "right_answer_wrong_reasoning"
    KEYWORD_STUFFED_NONSENSE = "keyword_stuffed_nonsense"
    CONFIDENT_BUT_IRRELEVANT = "confident_but_irrelevant"
    NONSTANDARD_VALID_METHOD = "nonstandard_valid_method"
    ILLEGIBLE_OR_GARBLED = "illegible_or_garbled"


class AdversarialCase(BaseModel):
    """One deliberately tricky question+answer pair, and what a robust grader should do with it.

    Unlike EvalCase (which checks numeric agreement with a human-graded score), this checks
    behavioral properties — did the grader catch the trick, or did it get fooled / unfairly punish
    a valid-but-unusual answer / confidently guess on something it should have flagged.
    """

    case_id: str
    trap: AdversarialTrap
    question: str
    student_answer: str
    subject: str = "general"
    expect_correct: bool | None = Field(
        default=None,
        description="If set, the grader's is_correct verdict for this question must match this to "
        "pass (e.g. False for nonsense/irrelevant answers, True for a valid alternate method). "
        "None means correctness isn't the thing being checked (e.g. illegibility cases).",
    )
    expect_flagged: bool | None = Field(
        default=None,
        description="If set, needs_human_review must match this. Traps designed to be genuinely "
        "ambiguous (nonstandard method, illegible) should expect True; clear-cut traps (nonsense, "
        "irrelevant) should expect False — a grader that hedges on everything is gaming the metric "
        "as much as one that never hedges.",
    )
    render_illegible: bool = Field(
        default=False,
        description="If true, the eval runner renders this case's answer with low contrast and "
        "jitter to simulate genuinely hard-to-read handwriting, instead of clean typed text — for "
        "cases where the trap is visual illegibility, not just nonsensical (but clearly legible) "
        "content.",
    )
    notes: str = Field(description="What this case is testing and why a naive grader might fail it")
